name: hs-practice
version: '0.1.0.0'
category: Undefined
author: OtaTakuma
maintainer: otatakuma0714@gmail.com
copyright: ! 'Copyright: (c) 2017 OtaTakuma'
license: BSD3
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5

executable:
  source-dirs: src
  main:        Main.hs


benchmarks:
  {{ name }}-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - {{ name }}
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

